version: "3.9"
    
services:
  wp:
    image: wordpress:latest
    container_name: wp
    hostname: wp
    ports:
      - ${WP_PORT-3000}:80
    volumes:
      - ./wp-app:/var/www/html
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      # - ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      - ./theme/born-to-give:/var/www/html/wp-content/themes/born-to-give # Theme development
    restart: unless-stopped	
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER-bandaloco}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD-password}
      WORDPRESS_DB_NAME: ${DB_NAME-bandaloco}
      WORDPRESS_DEBUG: 0
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '512M');
    networks:
      - eth
    depends_on:
      - db

  wpcli:
    image: wordpress:cli
    container_name: wpcli
    hostname: wpcli                                                                                                                    
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER-bandaloco}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD-password}
      WORDPRESS_DB_NAME: ${DB_NAME-bandaloco}
    networks:
      - eth
    depends_on:
      - db
      - wp

  db:
    image: mysql:latest
    container_name: db
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD-password}
      MYSQL_DATABASE: ${DB_NAME-bandaloco}
      MYSQL_USER: ${DB_USER-bandaloco}
      MYSQL_PASSWORD: ${DB_PASSWORD-password}
    networks:
      - eth

  # Gui Mysql
  dbeaver:
    image: dbeaver/cloudbeaver
    hostname: dbeaver
    container_name: dbeaver
    restart: unless-stopped
    entrypoint: /opt/cloudbeaver/docker-entrypoint.sh
    depends_on:
      - db
    ports:
      - 3080:8978
    volumes:
      - dbeaver_data:/opt/cloudbeaver/workspace
      - ./dbeaver/config/docker-entrypoint.sh:/opt/cloudbeaver/docker-entrypoint.sh
      - ./dbeaver/config/initial-data-sources.json:/opt/cloudbeaver/conf/initial-data-sources.conf
      - ./dbeaver/config/project-metadata.json:/opt/cloudbeaver/conf/project-metadata.conf
      - ./dbeaver/config/product.conf:/opt/cloudbeaver/conf/product.conf
      - ./dbeaver/config/cloudbeaver.conf:/opt/cloudbeaver/conf/cloudbeaver.conf
      - ./dbeaver/script:/opt/cloudbeaver/workspace/script
    environment:
      CB_ADMIN_NAME: ${DBEAVER_USER-admin@dbeaver}
      CB_ADMIN_PASSWORD: ${DBEAVAR_PASSWORD-password}
      CB_SERVER_NAME: dbeaver
    networks:
      eth:

volumes:
  db_data:
  dbeaver_data: 

networks:
  eth: