version: "3.9"
    
services:
  wp:
    image: wordpress:latest
    container_name: wp
    hostname: wp
    user: 1000:1000
    ports:
      - ${WP_PORT-3000}:80
    volumes:
      - wp_data:/var/www/html
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-plugins:/var/www/html/wp-content/plugins
      - ./wp-uploads:/var/www/html/wp-content/uploads
      # - ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      - ./theme/born-to-give:/var/www/html/wp-content/themes/born-to-give # Theme development
    restart: unless-stopped	
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER-bandaloco}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD-password}
      WORDPRESS_DB_NAME: ${DB_NAME-bandaloco}
      WORDPRESS_DEBUG: 0
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '512M');
    networks:
      - eth
    depends_on:
      - db

  wpcli:
    image: wordpress:cli
    container_name: wpcli
    hostname: wpcli                                                                                                                    
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER-bandaloco}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD-password}
      WORDPRESS_DB_NAME: ${DB_NAME-bandaloco}
    networks:
      - eth
    depends_on:
      - db
      - wp

  db:
    image: mariadb:latest
    container_name: db
    hostname: db
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD-password}
      MYSQL_DATABASE: ${DB_NAME-bandaloco}
      MYSQL_USER: ${DB_USER-bandaloco}
      MYSQL_PASSWORD: ${DB_PASSWORD-password}
    networks:
      - eth

volumes:
  db_data: 
  wp_data:

networks:
  eth: