version: "3.9"
    
services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bandaloco
      MYSQL_USER: bandaloco
      MYSQL_PASSWORD: password
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "3000:80"
    restart: unless-stopped	
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: bandaloco
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: bandaloco
volumes:
  db_data: {}
  wordpress_data: {}
