DOCKER_COMPOSE=docker-compose
COMPOSE_YML=docker-compose.yml
NETWORK_NAME=bl-eth

WP_SITE_URL=${WP_URL}
WP_SITE_NAME=${WP_NAME}
WP_SITE_DESCRIPTION=${WP_DESCRIPITION}
WP_SITE_USER = ${WP_ADMIN}
WP_SITE_PASSWORD = ${WP_PASSWORD}
WP_SITE_MAIL = ${WP_MAIL}
WP_AVADA= ${AVADA}
WP_SITE_LANG=it_IT
WP_SITE_TIMEZONE="Europe/Rome"
WP_SITE_DATE_FORMAT="j F Y"
WP_SITE_TIME_FORMAT="G:i"

WP_PAGE_7="Chi Siamo"
WP_PAGE_8="Il Territorio"
WP_PAGE_9="Eventi"
WP_PAGE_10="Tesseramento"
WP_PAGE_11="Documenti"
WP_PAGE_12="Contatti"