DOCKER_COMPOSE=docker-compose
COMPOSE_YML=docker-compose.yml
NETWORK_NAME=bl-eth

WP_URL=http://localhost:3000
WP_SITE_NAME=BandaLoco.dev
WP_SITE_USER = ${WP_ADMIN}
WP_SITE_PASSWORD = ${WP_PASSWORD}
WP_SITE_MAIL=bandariello@dev.loco
WP_SITE_LANG=it_IT
WP_SITE_TIMEZONE="Europe/Rome"
WP_SITE_DATE_FORMAT="j F Y"
WP_SITE_TIME_FORMAT="G:i"
