DOCKER_COMPOSE=docker-compose
COMPOSE_YML=docker-compose.yml
NETWORK_NAME=bl-eth

WP_SITE_URL=${WP_URL}
WP_SITE_NAME=${WP_NAME}
WP_SITE_DESCRIPTION=${WP_DESCRIPITION}
WP_SITE_USER = ${WP_ADMIN}
WP_SITE_PASSWORD = ${WP_PASSWORD}
WP_SITE_MAIL = ${WP_MAIL}
WP_AVADA= ${AVADA}
WP_SITE_LANG=it_IT
WP_SITE_TIMEZONE="Europe/Rome"
WP_SITE_DATE_FORMAT="j F Y"
WP_SITE_TIME_FORMAT="G:i"
